services:
  - type: web
    name: backend-addi-external
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
